# Generated by Django 5.1.6 on 2025-02-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0002_post_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='salary',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
