# Generated by Django 5.1.6 on 2025-02-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0003_alter_post_salary_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(default=models.CharField(max_length=101), max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=101),
        ),
    ]
