# Generated by Django 5.1.6 on 2025-02-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0004_alter_post_slug_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='salary',
            field=models.FloatField(),
        ),
    ]
