# Generated by Django 5.1.6 on 2025-02-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0006_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/images'),
        ),
    ]
