# Generated by Django 5.1.6 on 2025-02-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0007_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='tution/images'),
        ),
    ]
